name: ws_shelf_todos
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.17.0
  mongo_dart: ^0.10.4
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.0
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
